version: "3"

services: 
    tugo:
        container_name: tugo_back
        restart: always
        build: .
        ports: 
            - "5000:9000"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: mongodb
        image: mongo
        ports: 
            - "27017:27017"
        logging: 
            driver: none